import { useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import Modal from './components/Modal'
import { addDays, formatDate, formatShortDate, todayString } from './src/lib/dateUtils'
import { calculateStreaks, isScheduledOnDate } from './src/lib/streak'
import { createHabit, loadAppData, saveAppData } from './src/lib/storage'
import type { AppData, Habit, HabitDraft, ScheduleType } from './src/lib/types'

const COLORS = ['#f97316', '#0f766e', '#2563eb', '#db2777', '#7c3aed', '#65a30d']
const ICONS = ['💧', '📚', '🏃', '🍎', '🧘', '🎸', '🌱', '✍️']
const DAYS = ['S', 'M', 'T', 'W', 'T', 'F', 'S']
const emptyDraft: HabitDraft = { name: '', description: '', scheduleType: 'DAILY', customDays: [1, 2, 3, 4, 5], target: '', unit: '', emoji: '✨', color: COLORS[0] }

function challengeDay(start: string, today: string) {
  const days = Math.floor((new Date(`${today}T12:00:00`).getTime() - new Date(`${start}T12:00:00`).getTime()) / 86400000) + 1
  return Math.max(1, Math.min(75, days))
}

function draftFromHabit(habit: Habit): HabitDraft {
  return { name: habit.name, description: habit.description, scheduleType: habit.scheduleType, customDays: habit.customDays, target: habit.target?.toString() ?? '', unit: habit.unit, emoji: habit.emoji, color: habit.color }
}

function App() {
  const [data, setData] = useState<AppData>(() => loadAppData())
  const [view, setView] = useState<'today' | 'habits'>('today')
  const [editing, setEditing] = useState<Habit | undefined>()
  const [showForm, setShowForm] = useState(false)
  const [showHistory, setShowHistory] = useState<Habit | undefined>()
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState<'active' | 'archived' | 'all'>('active')
  const [scheduleFilter, setScheduleFilter] = useState<'ALL' | ScheduleType>('ALL')
  const today = todayString()

  const update = (next: AppData) => { setData(next); saveAppData(next) }
  const activeToday = data.habits.filter(h => !h.archived && isScheduledOnDate(h.scheduleType, h.customDays, today))
  const doneToday = activeToday.filter(h => h.completions.includes(today)).length
  const visibleHabits = useMemo(() => data.habits.filter(h => (filter === 'all' || (filter === 'archived' ? h.archived : !h.archived)) && (scheduleFilter === 'ALL' || h.scheduleType === scheduleFilter) && h.name.toLowerCase().includes(query.toLowerCase())), [data.habits, filter, scheduleFilter, query])
  const toggle = (habit: Habit, date = today) => {
    const has = habit.completions.includes(date)
    const completions = has ? habit.completions.filter(item => item !== date) : [...habit.completions, date].sort()
    update({ ...data, habits: data.habits.map(item => item.id === habit.id ? { ...item, completions } : item) })
  }
  const saveHabit = (draft: HabitDraft) => {
    const habit: Habit = { ...(editing ?? createHabit({ ...draft, target: draft.target ? Number(draft.target) : undefined, createdDate: today, archived: false, completions: [] })), ...draft, target: draft.target ? Number(draft.target) : undefined, customDays: [...draft.customDays] }
    update({ ...data, habits: editing ? data.habits.map(item => item.id === editing.id ? habit : item) : [...data.habits, habit] })
    setShowForm(false); setEditing(undefined)
  }
  const seed = () => update({ challengeStartDate: today, habits: [
    createHabit({ name: 'Drink water', description: 'Keep the bottle close.', scheduleType: 'DAILY', customDays: [], target: 8, unit: 'glasses', emoji: '💧', color: COLORS[2], createdDate: addDays(today, -6), archived: false, completions: [addDays(today, -5), addDays(today, -4), addDays(today, -3), addDays(today, -2)] }),
    createHabit({ name: 'Read', description: 'A few pages count.', scheduleType: 'DAILY', customDays: [], target: 20, unit: 'pages', emoji: '📚', color: COLORS[4], createdDate: addDays(today, -12), archived: false, completions: [addDays(today, -3), addDays(today, -2), addDays(today, -1)] }),
    createHabit({ name: 'Workout', description: 'Move with intention.', scheduleType: 'WEEKDAYS', customDays: [], unit: 'minutes', emoji: '🏃', color: COLORS[0], createdDate: addDays(today, -18), archived: false, completions: [addDays(today, -4), addDays(today, -3), addDays(today, -2)] }),
  ] })
  const archive = (habit: Habit) => update({ ...data, habits: data.habits.map(item => item.id === habit.id ? { ...item, archived: !item.archived } : item) })
  const remove = (habit: Habit) => { if (window.confirm(`Delete “${habit.name}” and its history?`)) update({ ...data, habits: data.habits.filter(item => item.id !== habit.id) }) }

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">S</span><span>streakly</span></div><p className="eyebrow">YOUR ROUTINE</p><nav><button className={view === 'today' ? 'nav-item active' : 'nav-item'} onClick={() => setView('today')}>◷ <span>Today</span><b>{doneToday}/{activeToday.length}</b></button><button className={view === 'habits' ? 'nav-item active' : 'nav-item'} onClick={() => setView('habits')}>▦ <span>All habits</span><b>{data.habits.filter(h => !h.archived).length}</b></button></nav><div className="challenge"><div className="challenge-top"><span>75 DAY CHALLENGE</span><strong>{challengeDay(data.challengeStartDate, today)}<small>/75</small></strong></div><div className="progress"><span style={{ width: `${challengeDay(data.challengeStartDate, today) / 75 * 100}%` }} /></div><p>{data.habits.length ? 'Small steps, stacked daily.' : 'Your next chapter starts here.'}</p></div><button className="seed-button" onClick={seed}>✦ Load demo habits</button><div className="sidebar-foot"><span className="status-dot" /> Stored locally<br /><small>Private to this browser</small></div></aside>
    <main className="main-content"><header className="topbar"><div><p className="kicker">{formatDate(today, { weekday: 'long' }).toUpperCase()}</p><h1>{view === 'today' ? 'Make today count.' : 'Your habits.'}</h1></div><button className="add-button" onClick={() => { setEditing(undefined); setShowForm(true) }}>＋ <span>New habit</span></button></header>{view === 'today' ? <TodayView habits={activeToday} today={today} toggle={toggle} onOpen={setShowHistory} onNew={() => setShowForm(true)} /> : <HabitLibrary habits={visibleHabits} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} scheduleFilter={scheduleFilter} setScheduleFilter={setScheduleFilter} onEdit={habit => { setEditing(habit); setShowForm(true) }} onHistory={setShowHistory} onArchive={archive} onDelete={remove} onNew={() => { setEditing(undefined); setShowForm(true) }} />}</main>
    {showForm && <HabitForm initial={editing ? draftFromHabit(editing) : emptyDraft} onClose={() => { setShowForm(false); setEditing(undefined) }} onSave={saveHabit} />}{showHistory && <History habit={showHistory} today={today} onClose={() => setShowHistory(undefined)} onToggle={date => toggle(showHistory, date)} />}
  </div>
}

function TodayView({ habits, today, toggle, onOpen, onNew }: { habits: Habit[]; today: string; toggle: (habit: Habit) => void; onOpen: (habit: Habit) => void; onNew: () => void }) { const done = habits.filter(h => h.completions.includes(today)).length; return <section className="today-view"><div className="date-line"><span>{formatDate(today)}</span><span className="progress-label">{done} of {habits.length} complete</span></div>{habits.length > 0 && <div className="today-progress"><span style={{ width: `${done / habits.length * 100}%` }} /></div>}<div className="habit-stack">{habits.map(habit => <HabitRow key={habit.id} habit={habit} today={today} onToggle={() => toggle(habit)} onOpen={() => onOpen(habit)} />)}</div>{habits.length === 0 && <EmptyToday onNew={onNew} />}</section> }
function HabitRow({ habit, today, onToggle, onOpen }: { habit: Habit; today: string; onToggle: () => void; onOpen: () => void }) { const checked = habit.completions.includes(today); const streak = calculateStreaks(habit, today); return <article className={checked ? 'habit-row complete' : 'habit-row'}><button className="check" style={{ borderColor: habit.color, background: checked ? habit.color : 'transparent' }} onClick={onToggle} aria-label={`Mark ${habit.name} ${checked ? 'incomplete' : 'complete'}`}>{checked ? '✓' : ''}</button><button className="habit-main" onClick={onOpen}><span className="habit-icon" style={{ background: `${habit.color}18` }}>{habit.emoji}</span><span className="habit-copy"><strong>{habit.name}</strong><small>{habit.description || scheduleText(habit)}{habit.target ? ` · ${habit.target} ${habit.unit}` : ''}</small></span></button><span className="streak-stat"><b>🔥 {streak.current}</b><small>day streak</small></span><span className="best-stat"><b>{streak.best}</b><small>best</small></span></article> }
function EmptyToday({ onNew }: { onNew: () => void }) { return <div className="empty-state"><div className="empty-icon">☀</div><h2>A clear slate.</h2><p>No habits are scheduled for today. Add one and make it yours.</p><button className="primary-button" onClick={onNew}>＋ Create your first habit</button></div> }

function HabitLibrary({ habits, query, setQuery, filter, setFilter, scheduleFilter, setScheduleFilter, onEdit, onHistory, onArchive, onDelete, onNew }: { habits: Habit[]; query: string; setQuery: (v: string) => void; filter: 'active' | 'archived' | 'all'; setFilter: (v: 'active' | 'archived' | 'all') => void; scheduleFilter: 'ALL' | ScheduleType; setScheduleFilter: (v: 'ALL' | ScheduleType) => void; onEdit: (h: Habit) => void; onHistory: (h: Habit) => void; onArchive: (h: Habit) => void; onDelete: (h: Habit) => void; onNew: () => void }) { return <section className="library"><div className="toolbar"><label className="search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search habits..." /></label><select value={scheduleFilter} onChange={e => setScheduleFilter(e.target.value as 'ALL' | ScheduleType)}><option value="ALL">All schedules</option><option value="DAILY">Daily</option><option value="WEEKDAYS">Weekdays</option><option value="CUSTOM">Custom</option></select></div><div className="filter-tabs">{(['active', 'archived', 'all'] as const).map(item => <button className={filter === item ? 'selected' : ''} key={item} onClick={() => setFilter(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div>{habits.length ? <div className="library-grid">{habits.map(habit => <HabitCard key={habit.id} habit={habit} onEdit={() => onEdit(habit)} onHistory={() => onHistory(habit)} onArchive={() => onArchive(habit)} onDelete={() => onDelete(habit)} />)}</div> : <div className="empty-library"><h2>No habits found.</h2><p>Try another search or create something new.</p><button className="primary-button" onClick={onNew}>＋ New habit</button></div>}</section> }
function HabitCard({ habit, onEdit, onHistory, onArchive, onDelete }: { habit: Habit; onEdit: () => void; onHistory: () => void; onArchive: () => void; onDelete: () => void }) { const streak = calculateStreaks(habit); return <article className="habit-card" style={{ borderTopColor: habit.color }}><div className="card-head"><span className="card-icon">{habit.emoji}</span><div><h3>{habit.name}</h3><p>{scheduleText(habit)}{habit.archived && ' · Archived'}</p></div><button className="icon-button" onClick={onEdit} aria-label={`Edit ${habit.name}`}>✎</button></div>{habit.description && <p className="card-description">{habit.description}</p>}<div className="card-stats"><div><strong>🔥 {streak.current}</strong><small>Current</small></div><div><strong>{streak.best}</strong><small>Best streak</small></div><div><strong>{completionRate(habit)}%</strong><small>Completion</small></div></div><div className="card-actions"><button onClick={onHistory}>History</button><button onClick={onArchive}>{habit.archived ? 'Unarchive' : 'Archive'}</button><button className="danger" onClick={onDelete}>Delete</button></div></article> }

function HabitForm({ initial, onClose, onSave }: { initial: HabitDraft; onClose: () => void; onSave: (draft: HabitDraft) => void }) { const [draft, setDraft] = useState(initial); const submit = (event: FormEvent) => { event.preventDefault(); if (draft.name.trim() && (draft.scheduleType !== 'CUSTOM' || draft.customDays.length)) onSave({ ...draft, name: draft.name.trim() }) }; return <Modal title={initial.name ? 'Edit habit' : 'New habit'} onClose={onClose}><form className="habit-form" onSubmit={submit}><label>Habit name<input autoFocus required value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} placeholder="e.g. Drink water" /></label><label>Description <span className="optional">optional</span><input value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} placeholder="A little context goes a long way" /></label><fieldset><legend>Schedule</legend><div className="schedule-options">{(['DAILY', 'WEEKDAYS', 'CUSTOM'] as ScheduleType[]).map(type => <button type="button" className={draft.scheduleType === type ? 'schedule-choice selected' : 'schedule-choice'} key={type} onClick={() => setDraft({ ...draft, scheduleType: type })}>{type === 'DAILY' ? 'Every day' : type === 'WEEKDAYS' ? 'Weekdays' : 'Custom days'}</button>)}</div>{draft.scheduleType === 'CUSTOM' && <div className="day-picker">{DAYS.map((day, index) => <button type="button" className={draft.customDays.includes(index) ? 'day selected' : 'day'} key={`${day}-${index}`} onClick={() => setDraft({ ...draft, customDays: draft.customDays.includes(index) ? draft.customDays.filter(item => item !== index) : [...draft.customDays, index].sort() })}>{day}</button>)}</div>}</fieldset><div className="form-split"><label>Target <span className="optional">optional</span><input type="number" min="0" value={draft.target} onChange={e => setDraft({ ...draft, target: e.target.value })} placeholder="8" /></label><label>Unit <span className="optional">optional</span><input value={draft.unit} onChange={e => setDraft({ ...draft, unit: e.target.value })} placeholder="glasses" /></label></div><div><label>Icon</label><div className="icon-picker">{ICONS.map(icon => <button type="button" className={draft.emoji === icon ? 'picked' : ''} key={icon} onClick={() => setDraft({ ...draft, emoji: icon })}>{icon}</button>)}</div></div><div><label>Color</label><div className="color-picker">{COLORS.map(color => <button type="button" aria-label="Choose color" className={draft.color === color ? 'color picked' : 'color'} style={{ background: color }} key={color} onClick={() => setDraft({ ...draft, color })} />)}</div></div><div className="form-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" type="submit">Save habit</button></div></form></Modal> }

function History({ habit, today, onClose, onToggle }: { habit: Habit; today: string; onClose: () => void; onToggle: (date: string) => void }) { const dates = Array.from({ length: 30 }, (_, index) => addDays(today, index - 29)); return <Modal title={`${habit.emoji} ${habit.name}`} subtitle="Last 30 days · click a scheduled day to backfill" onClose={onClose}><div className="history"><div className="history-summary"><div><strong>{completionRate(habit)}%</strong><span>completion rate</span></div><div><strong>🔥 {calculateStreaks(habit, today).current}</strong><span>current streak</span></div><div><strong>{calculateStreaks(habit, today).best}</strong><span>best streak</span></div></div><div className="heatmap">{dates.map(date => { const scheduled = isScheduledOnDate(habit.scheduleType, habit.customDays, date); const complete = habit.completions.includes(date); return <button key={date} disabled={!scheduled || date > today} className={`heat-dot ${complete ? 'done' : scheduled ? 'missed' : 'off'}`} onClick={() => onToggle(date)} title={`${formatShortDate(date)}${complete ? ' · complete' : scheduled ? ' · mark complete' : ' · not scheduled'}`} /> })}</div><div className="heat-legend"><span><i className="heat-dot done" /> Complete</span><span><i className="heat-dot missed" /> Scheduled</span><span><i className="heat-dot off" /> Rest day</span></div></div></Modal> }

function scheduleText(habit: Pick<Habit, 'scheduleType' | 'customDays'>) { if (habit.scheduleType === 'DAILY') return 'Every day'; if (habit.scheduleType === 'WEEKDAYS') return 'Weekdays'; return habit.customDays.length ? habit.customDays.map(day => DAYS[day]).join(' · ') : 'No days selected' }
function completionRate(habit: Habit) { const end = todayString(); const start = habit.createdDate > addDays(end, -29) ? habit.createdDate : addDays(end, -29); let scheduled = 0; for (let date = start; date <= end; date = addDays(date, 1)) if (isScheduledOnDate(habit.scheduleType, habit.customDays, date)) scheduled++; return scheduled ? Math.round(habit.completions.filter(date => date >= start && date <= end).length / scheduled * 100) : 0 }
export default App